apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxsendtest
  labels:
    app: maxsendtest
spec:
  replicas: 7
  selector:
    matchLabels:
      app: maxsendtest
  template:
    metadata:
      labels:
          app: maxsendtest
    spec:
      containers:
        - name: testhub
          image: devigned/testhub:v0.0.9
          imagePullPolicy: Always
          command: ["./testhub"]
          args: [
            "max-send-test",
            "--conn-str=$(EVENTHUB_CONNECTION_STRING)",
            "--num-senders", "1",
            "--partition-count", "128"
          ]
          env:
            - name: EVENTHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: hundredtuconnstr
                  key: connStr

