apiVersion: apps/v1
kind: Deployment
metadata:
  name: max_send_test
  labels:
    app: max_send_test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: max_send_test
  template:
    metadata:
      labels:
          app: max_send_test
    spec:
      containers:
        - name: testhub
          image: devigned/testhub:latest
          imagePullPolicy: Always
          command: ["testhub"]
          args: ["max-send-test", "--conn-str='$(EVENTHUB_CONNECTION_STRING)'", "--num-senders 20"]
          env:
            - name: EVENTHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: go-0-3627d-1
                  key: connStr

